### ISSUE TITLE
vim-cljreloaded seems to need a active repl connection when loading the plugin. 

### ISSUE THREAD

**Issue by zamaterian** [markwoodhall/vim-cljreloaded#1]
with Plug 'markwoodhall/vim-cljreloaded' :   

Error detected while processing function fireplace#eval[1]..fireplace#session_eval[1]..<SNR>49_eval[2]..fireplace#client[2]..fireplace#platform:
line   32:
E605: Exception not caught: Fireplace: :Connect to a REPL or install classpath.vim
Error detected while processing /home/te/.vim/plugged/vim-cljreloaded/plugin/cljreloaded.vim:
line   82:
E171: Missing :endif

with Plug 'markwoodhall/vim-cljreloaded', { 'for': [] }

No problems - but the plug must be loaded manually after a repl is started

**Comment by markwoodhall** [comment]
Thanks for letting me know about this, I appreciate it. Hopefully the above commit should resolve the issue. 

Let me know if you spot anything else.
